/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type { IDefinaCard, IDefinaCardInterface } from "../IDefinaCard";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "cardId_",
        type: "uint256",
      },
    ],
    name: "mint",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
    ],
    name: "safeTransferFrom",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IDefinaCard__factory {
  static readonly abi = _abi;
  static createInterface(): IDefinaCardInterface {
    return new utils.Interface(_abi) as IDefinaCardInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IDefinaCard {
    return new Contract(address, _abi, signerOrProvider) as IDefinaCard;
  }
}
