/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IERC777SenderUpgradeable,
  IERC777SenderUpgradeableInterface,
} from "../IERC777SenderUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "operator",
        type: "address",
      },
      {
        internalType: "address",
        name: "from",
        type: "address",
      },
      {
        internalType: "address",
        name: "to",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "amount",
        type: "uint256",
      },
      {
        internalType: "bytes",
        name: "userData",
        type: "bytes",
      },
      {
        internalType: "bytes",
        name: "operatorData",
        type: "bytes",
      },
    ],
    name: "tokensToSend",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IERC777SenderUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): IERC777SenderUpgradeableInterface {
    return new utils.Interface(_abi) as IERC777SenderUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IERC777SenderUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as IERC777SenderUpgradeable;
  }
}
