/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomConsumer,
  IRandomConsumerInterface,
} from "../IRandomConsumer";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId_",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user_",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "randomness_",
        type: "uint256",
      },
    ],
    name: "runFulfillRandomness",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandomConsumer__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomConsumerInterface {
    return new utils.Interface(_abi) as IRandomConsumerInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomConsumer {
    return new Contract(address, _abi, signerOrProvider) as IRandomConsumer;
  }
}
