/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  IRandomGenerator,
  IRandomGeneratorInterface,
} from "../IRandomGenerator";

const _abi = [
  {
    inputs: [
      {
        internalType: "uint256",
        name: "tokenId",
        type: "uint256",
      },
      {
        internalType: "address",
        name: "user",
        type: "address",
      },
    ],
    name: "requestRandomNumber",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class IRandomGenerator__factory {
  static readonly abi = _abi;
  static createInterface(): IRandomGeneratorInterface {
    return new utils.Interface(_abi) as IRandomGeneratorInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): IRandomGenerator {
    return new Contract(address, _abi, signerOrProvider) as IRandomGenerator;
  }
}
