/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Logic, LogicInterface } from "../Logic";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    name: "Added",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Fallback",
    type: "event",
  },
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "add",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x6080604052600a60005534801561001557600080fd5b50610152806100256000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c80632096525514610061578063771602f714610077575b6040517f52b4643cca14f009d3eef2bb2517ebc5918c9152c5038af8258985bdd6ca258090600090a1005b6000545b60405190815260200160405180910390f35b6100656100853660046100d4565b60008061009283856100f6565b60008190556040518181529091507f64a55044d1f2eddebe1b90e8e2853e8e96931cefadbfa0b2ceb34bee360619419060200160405180910390a19392505050565b600080604083850312156100e757600080fd5b50508035926020909101359150565b6000821982111561011757634e487b7160e01b600052601160045260246000fd5b50019056fea2646970667358221220af66110f139d3c0e7504f6be0b26889e6251f6291c947d8f284080fe6378f76d64736f6c63430008090033";

export class Logic__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Logic> {
    return super.deploy(overrides || {}) as Promise<Logic>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Logic {
    return super.attach(address) as Logic;
  }
  connect(signer: Signer): Logic__factory {
    return super.connect(signer) as Logic__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LogicInterface {
    return new utils.Interface(_abi) as LogicInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Logic {
    return new Contract(address, _abi, signerOrProvider) as Logic;
  }
}
