/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type { Logic, LogicInterface } from "../Logic";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "uint256",
        name: "result",
        type: "uint256",
      },
    ],
    name: "Added",
    type: "event",
  },
  {
    anonymous: false,
    inputs: [],
    name: "Fallback",
    type: "event",
  },
  {
    stateMutability: "nonpayable",
    type: "fallback",
  },
  {
    inputs: [
      {
        internalType: "uint256",
        name: "a",
        type: "uint256",
      },
      {
        internalType: "uint256",
        name: "b",
        type: "uint256",
      },
    ],
    name: "add",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "getValue",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [],
    name: "initial",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610332806100206000396000f3fe608060405234801561001057600080fd5b50600436106100415760003560e01c8063209652551461006c578063771602f714610081578063bb806dc914610096575b6040517f52b4643cca14f009d3eef2bb2517ebc5918c9152c5038af8258985bdd6ca258090600090a1005b60005460405190815260200160405180910390f35b61009461008f366004610212565b6100a0565b005b610094600a600055565b6100d06040518060400160405280600c81526020016b03732bb902b30b63ab2901e960a51b81525060005461015c565b6101106040518060400160405280601f81526020017f6d73672e73656e646572203d2025732c2074782e6f726967696e203d2025730081525033326101a5565b600061011c8284610234565b60008190556040518181529091507f64a55044d1f2eddebe1b90e8e2853e8e96931cefadbfa0b2ceb34bee360619419060200160405180910390a1505050565b6101a182826040516024016101729291906102a7565b60408051601f198184030181529190526020810180516001600160e01b03166309710a9d60e41b1790526101f1565b5050565b6101ec8383836040516024016101bd939291906102c9565b60408051601f198184030181529190526020810180516001600160e01b03166307e763af60e51b1790526101f1565b505050565b80516a636f6e736f6c652e6c6f67602083016000808483855afa5050505050565b6000806040838503121561022557600080fd5b50508035926020909101359150565b6000821982111561025557634e487b7160e01b600052601160045260246000fd5b500190565b6000815180845260005b8181101561028057602081850181015186830182015201610264565b81811115610292576000602083870101525b50601f01601f19169290920160200192915050565b6040815260006102ba604083018561025a565b90508260208301529392505050565b6060815260006102dc606083018661025a565b6001600160a01b039485166020840152929093166040909101529291505056fea264697066735822122088ae3f0aab4c3f6101b7c983281b110d6ca6f662cc848a2a634ecdd3cbd7a43564736f6c63430008090033";

export class Logic__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<Logic> {
    return super.deploy(overrides || {}) as Promise<Logic>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): Logic {
    return super.attach(address) as Logic;
  }
  connect(signer: Signer): Logic__factory {
    return super.connect(signer) as Logic__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): LogicInterface {
    return new utils.Interface(_abi) as LogicInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Logic {
    return new Contract(address, _abi, signerOrProvider) as Logic;
  }
}
