/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from "ethers";
import { Provider } from "@ethersproject/providers";
import type {
  PullPaymentUpgradeable,
  PullPaymentUpgradeableInterface,
} from "../PullPaymentUpgradeable";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "dest",
        type: "address",
      },
    ],
    name: "payments",
    outputs: [
      {
        internalType: "uint256",
        name: "",
        type: "uint256",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
  {
    inputs: [
      {
        internalType: "address payable",
        name: "payee",
        type: "address",
      },
    ],
    name: "withdrawPayments",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

export class PullPaymentUpgradeable__factory {
  static readonly abi = _abi;
  static createInterface(): PullPaymentUpgradeableInterface {
    return new utils.Interface(_abi) as PullPaymentUpgradeableInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): PullPaymentUpgradeable {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as PullPaymentUpgradeable;
  }
}
